'use client';

import React from 'react';

const AdidhiPrivacyPolicy: React.FC = () => {
  return (
    <div className="bg-gray-50 px-6 py-10">
      <div className="mx-auto max-w-5xl rounded-lg bg-white p-6 shadow-md">
        <h1 className="mb-6 text-center text-2xl font-bold text-gray-800 md:text-4xl">
          Privacy Policy for Adidhi Hospitality
        </h1>

        <p className="mb-2 text-sm text-gray-600">
          <strong>Last updated:</strong>
          {' '}
          January 27, 2025
        </p>

        <p className="mb-4 text-gray-700">
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>

        <p className="mb-4 text-gray-700">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        {/* Interpretation and Definitions */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Interpretation and Definitions</h2>

        <h3 className="mb-2 text-lg font-semibold text-gray-800">Interpretation</h3>
        <p className="mb-4 text-gray-700">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="mb-2 text-lg font-semibold text-gray-800">Definitions</h3>
        <p className="mb-4 text-gray-700">For the purposes of this Privacy Policy:</p>
        <ul className="mb-4 list-inside list-disc space-y-2 text-gray-700">
          <li>
            <strong>Account:</strong>
            {' '}
            A unique account created for You to access our Service.
          </li>
          <li>
            <strong>Affiliate:</strong>
            {' '}
            An entity that controls, is controlled by, or is under common control with a party.
          </li>
          <li>
            <strong>Application:</strong>
            {' '}
            Refers to Adidhi Hospitality, the software program provided by the Company.
          </li>
          <li>
            <strong>Company:</strong>
            {' '}
            Adidhi Hospitality Private Limited.
          </li>
          <li>
            <strong>Country:</strong>
            {' '}
            Refers to Kerala, India.
          </li>
          <li>
            <strong>Device:</strong>
            {' '}
            Any device that can access the Service such as a computer, a cellphone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data:</strong>
            {' '}
            Information that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>Service:</strong>
            {' '}
            Refers to the Application.
          </li>
          <li>
            <strong>Service Provider:</strong>
            {' '}
            A natural or legal person who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Usage Data:</strong>
            {' '}
            Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
          </li>
          <li>
            <strong>You:</strong>
            {' '}
            The individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.
          </li>
        </ul>

        {/* Collecting and Using Your Personal Data */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Collecting and Using Your Personal Data</h2>

        <h3 className="mb-2 text-lg font-semibold text-gray-800">Types of Data Collected</h3>

        <h4 className="mb-2 font-semibold text-gray-800">Personal Data</h4>
        <p className="mb-4 text-gray-700">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="mb-4 list-inside list-disc space-y-2 text-gray-700">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
        </ul>

        <h4 className="mb-2 font-semibold text-gray-800">Usage Data</h4>
        <p className="mb-4 text-gray-700">
          Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time spent on those pages, and other diagnostic data.
        </p>

        {/* Retention of Your Personal Data */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Retention of Your Personal Data</h2>
        <p className="mb-4 text-gray-700">
          The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. We will retain Usage Data for internal analysis purposes to strengthen security or improve functionality.
        </p>

        {/* Security of Your Personal Data */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Security of Your Personal Data</h2>
        <p className="mb-4 text-gray-700">
          The security of Your Personal Data is important to Us. However, no method of transmission over the Internet is 100% secure.
        </p>

        {/* Children's Privacy */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Children's Privacy</h2>
        <p className="mb-4 text-gray-700">
          Our Service does not address anyone under the age of 13. If We become aware that We have collected Personal Data from anyone under 13 without parental consent, We will take steps to remove that information.
        </p>

        {/* Changes to this Privacy Policy */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Changes to this Privacy Policy</h2>
        <p className="mb-4 text-gray-700">
          We may update Our Privacy Policy from time to time. Changes to this Privacy Policy are effective when posted on this page.
        </p>

        {/* Contact Us */}
        <h2 className="mb-4 mt-6 text-xl font-bold text-gray-800">Contact Us</h2>
        <p className="text-gray-700">
          If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <ul className="list-inside list-disc space-y-2 text-gray-700">
          <li>
            By email:
            <a href="mailto:support@adidhi.com" className="text-blue-500 hover:underline">support@adidhi.com</a>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default AdidhiPrivacyPolicy;
